id: p27_trim_edges
title: p27_trim_edges
origin: piscine27
version: v0
module: p27_02_strings
level: 0
type: c_program
language: c
expected_files:
  - p27_trim_edges.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_02_strings/p27_trim_edges/profile.yml
