id: ft_print_combn
title: ft_print_combn
origin: piscine42
version: v1
module: c00
level: 8
type: c_function
language: c
expected_files:
- ft_print_combn.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: void ft_print_combn(int n)
tags:
- c00
- piscine
correction:
  profile: corrections/piscine/c00/ft_print_combn/profile.yml
