id: p27_map_reader
title: p27_map_reader
origin: piscine27
version: v0
module: p27_07_files
level: 0
type: c_program
language: c
expected_files:
  - p27_map_reader.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_07_files/p27_map_reader/profile.yml
