id: p27_join_words
title: p27_join_words
origin: piscine27
version: v0
module: p27_06_memory_malloc
level: 0
type: c_program
language: c
expected_files:
  - p27_join_words.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_06_memory_malloc/p27_join_words/profile.yml
