id: p27_toolbox
title: p27_toolbox
origin: piscine27
version: v0
module: p27_final
level: 0
type: c_program
language: c
expected_files:
  - p27_toolbox.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_final/p27_toolbox/profile.yml
