id: ft_strupcase
title: ft_strupcase
origin: piscine42
version: v1
module: c02
level: 7
type: c_function
language: c
expected_files:
- ft_strupcase.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: char *ft_strupcase(char *str)
tags:
- c02
- piscine
correction:
  profile: corrections/piscine/c02/ft_strupcase/profile.yml
