id: p27_permissions_lab
title: p27_permissions_lab
origin: piscine27
version: v0
module: p27_00_terminal_survival
level: 0
type: shell
language: sh
expected_files:
  - p27_permissions_lab.sh
allowed_functions:
  - write
norminette: false
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_00_terminal_survival/p27_permissions_lab/profile.yml
