id: ft_strlen
title: ft_strlen
origin: piscine42
version: v1
module: c04
level: 0
type: c_function
language: c
expected_files:
- ft_strlen.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: int ft_strlen(char *str)
tags:
- c04
- piscine
correction:
  profile: corrections/piscine/c04/ft_strlen/profile.yml
