id: frog_sha1_manifest
title: frog_sha1_manifest
origin: frog42
version: v2
module: nova_batch_06
level: 7
type: shell
language: sh
expected_files:
- frog_sha1_manifest.sh
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: false
tags:
- frog42
- nova
- v2
