id: z
title: z
origin: piscine42
version: v1
module: shell00
level: 0
type: shell
language: sh
expected_files:
- testShell00.tar
norminette: false
tags:
- shell00
- piscine
correction:
  profile: corrections/piscine/shell00/z/profile.yml
validator_only: true
