id: p27_sum_numbers
title: p27_sum_numbers
origin: piscine27
version: v0
module: p27_04_parsing
level: 0
type: c_program
language: c
expected_files:
  - p27_sum_numbers.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_04_parsing/p27_sum_numbers/profile.yml
