id: p27_split_malloc
title: p27_split_malloc
origin: piscine27
version: v0
module: p27_06_memory_malloc
level: 0
type: c_program
language: c
expected_files:
  - p27_split_malloc.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_06_memory_malloc/p27_split_malloc/profile.yml
