id: p27_ascii_window
title: p27_ascii_window
origin: piscine27
version: v0
module: p27_01_c_output
level: 0
type: c_program
language: c
expected_files:
  - p27_ascii_window.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_01_c_output/p27_ascii_window/profile.yml
