id: p27_strlen_trace
title: p27_strlen_trace
origin: piscine27
version: v0
module: p27_02_strings
level: 0
type: c_program
language: c
expected_files:
  - p27_strlen_trace.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_02_strings/p27_strlen_trace/profile.yml
