id: frog_pipe_alphabet
title: frog_pipe_alphabet
origin: frog42
version: v2
module: nova_batch_05
level: 0
type: shell
language: sh
expected_files:
- frog_pipe_alphabet.sh
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: false
tags:
- frog42
- nova
- v2
