id: p27_zigzag_alpha
title: p27_zigzag_alpha
origin: piscine27
version: v0
module: p27_03_ascii_transformations
level: 0
type: c_program
language: c
expected_files:
  - p27_zigzag_alpha.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_03_ascii_transformations/p27_zigzag_alpha/profile.yml
