id: git_ignore.sh
title: git_ignore.sh
origin: piscine42
version: v1
module: shell00
level: 6
type: shell
language: sh
expected_files:
- git_ignore.sh
norminette: false
tags:
- shell00
- piscine
correction:
  profile: corrections/piscine/shell00/git_ignore.sh/profile.yml
