id: p27_find_cleaner
title: p27_find_cleaner
origin: piscine27
version: v0
module: p27_00_terminal_survival
level: 0
type: shell
language: sh
expected_files:
  - p27_find_cleaner.sh
allowed_functions:
  - write
norminette: false
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_00_terminal_survival/p27_find_cleaner/profile.yml
