id: ft_atoi
title: ft_atoi
origin: piscine42
version: v1
module: c04
level: 3
type: c_function
language: c
expected_files:
- ft_atoi.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: int ft_atoi(char *str)
tags:
- c04
- piscine
correction:
  profile: corrections/piscine/c04/ft_atoi/profile.yml
