id: p27_mini_moulinette
title: p27_mini_moulinette
origin: piscine27
version: v0
module: p27_final
level: 0
type: c_program
language: c
expected_files:
  - p27_mini_moulinette.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_final/p27_mini_moulinette/profile.yml
