id: frog_make_hardlink_pair
title: frog_make_hardlink_pair
origin: frog42
version: v2
module: nova_batch_06
level: 1
type: shell
language: sh
expected_files:
- frog_make_hardlink_pair.sh
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: false
tags:
- frog42
- nova
- v2
