id: frog_log_rotate_lite
title: frog_log_rotate_lite
origin: frog42
version: v2
module: nova_batch_06
level: 9
type: shell
language: sh
expected_files:
- frog_log_rotate_lite.sh
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: false
tags:
- frog42
- nova
- v2
