id: ft_strcapitalize
title: ft_strcapitalize
origin: piscine42
version: v1
module: c02
level: 9
type: c_function
language: c
expected_files:
- ft_strcapitalize.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: char *ft_strcapitalize(char *str)
tags:
- c02
- piscine
correction:
  profile: corrections/piscine/c02/ft_strcapitalize/profile.yml
