id: frog_param_sorter
title: frog_param_sorter
origin: frog42
version: v2
module: nova_batch_02
level: 3
type: c_program
language: c
expected_files:
- frog_param_sorter.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
tags:
- frog42
- nova
- v2
