id: ft_swap
title: ft_swap
origin: piscine42
version: v1
module: c01
level: 2
type: c_function
language: c
expected_files:
- ft_swap.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: void ft_swap(int *a, int *b)
tags:
- c01
- piscine
correction:
  profile: corrections/piscine/c01/ft_swap/profile.yml
