id: frog_hidden_files_map
title: frog_hidden_files_map
origin: frog42
version: v2
module: nova_batch_05
level: 3
type: shell
language: sh
expected_files:
- frog_hidden_files_map.sh
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: false
tags:
- frog42
- nova
- v2
