id: ft_print_reverse_alphabet
title: ft_print_reverse_alphabet
origin: piscine42
version: v1
module: c00
level: 2
type: c_function
language: c
expected_files:
- ft_print_reverse_alphabet.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: void ft_print_reverse_alphabet(void)
tags:
- c00
- piscine
correction:
  profile: corrections/piscine/c00/ft_print_reverse_alphabet/profile.yml
