id: p27_git_time_machine
title: p27_git_time_machine
origin: piscine27
version: v0
module: p27_00_terminal_survival
level: 0
type: shell
language: sh
expected_files:
  - p27_git_time_machine.sh
allowed_functions:
  - write
norminette: false
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_00_terminal_survival/p27_git_time_machine/profile.yml
