id: ft_atoi_base
title: ft_atoi_base
origin: piscine42
version: v1
module: c04
level: 5
type: c_function
language: c
expected_files:
- ft_atoi_base.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: int ft_atoi_base(char *str, char *base)
tags:
- c04
- piscine
correction:
  profile: corrections/piscine/c04/ft_atoi_base/profile.yml
