id: ft_ultimate_div_mod
title: ft_ultimate_div_mod
origin: piscine42
version: v1
module: c01
level: 4
type: c_function
language: c
expected_files:
- ft_ultimate_div_mod.c
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: true
prototype: void ft_ultimate_div_mod(int *a, int *b)
tags:
- c01
- piscine
correction:
  profile: corrections/piscine/c01/ft_ultimate_div_mod/profile.yml
