id: frog_touch_timestamp
title: frog_touch_timestamp
origin: frog42
version: v2
module: nova_batch_06
level: 3
type: shell
language: sh
expected_files:
- frog_touch_timestamp.sh
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: false
tags:
- frog42
- nova
- v2
