id: p27_count_words
title: p27_count_words
origin: piscine27
version: v0
module: p27_02_strings
level: 0
type: c_program
language: c
expected_files:
  - p27_count_words.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_02_strings/p27_count_words/profile.yml
