id: p27_putchar_trace
title: p27_putchar_trace
origin: piscine27
version: v0
module: p27_01_c_output
level: 0
type: c_program
language: c
expected_files:
  - p27_putchar_trace.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_01_c_output/p27_putchar_trace/profile.yml
