id: p27_queue_bfs
title: p27_queue_bfs
origin: piscine27
version: v0
module: p27_08_data_structures
level: 0
type: c_program
language: c
expected_files:
  - p27_queue_bfs.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_08_data_structures/p27_queue_bfs/profile.yml
