id: frog_weird_filename
title: frog_weird_filename
origin: frog42
version: v2
module: nova_batch_06
level: 6
type: shell
language: sh
expected_files:
- frog_weird_filename.sh
allowed_functions:
- write
forbidden_functions:
- printf
- puts
- fprintf
norminette: false
tags:
- frog42
- nova
- v2
