id: p27_list_sort
title: p27_list_sort
origin: piscine27
version: v0
module: p27_08_data_structures
level: 0
type: c_program
language: c
expected_files:
  - p27_list_sort.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_08_data_structures/p27_list_sort/profile.yml
