id: p27_maze_path
title: p27_maze_path
origin: piscine27
version: v0
module: p27_09_maps_algorithms
level: 0
type: c_program
language: c
expected_files:
  - p27_maze_path.c
allowed_functions:
  - write
norminette: true
tags:
  - piscine27
correction:
  profile: corrections/piscine27/p27_09_maps_algorithms/p27_maze_path/profile.yml
